"""initial - 44 tables

Revision ID: 887523eb9099
Revises: 
Create Date: 2026-04-12 22:04:51.967475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '887523eb9099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('tool_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('tax_type', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'effective_date')
    )
    op.create_index(op.f('ix_exchange_rate_effective_date'), 'exchange_rate', ['effective_date'], unique=False)
    op.create_table('knowledge_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('applicable_doc_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entry_entry_type'), 'knowledge_entry', ['entry_type'], unique=False)
    op.create_table('material_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['material_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(length=15), nullable=False),
    sa.Column('balance_direction', sa.String(length=10), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code')
    )
    op.create_index(op.f('ix_account_code'), 'account', ['code'], unique=False)
    op.create_table('fiscal_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounting_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_id', 'period_number')
    )
    op.create_table('agent_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('tools_called', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_log_timestamp'), 'agent_log', ['timestamp'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('code_type', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('default_shipping_method', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code')
    )
    op.create_index(op.f('ix_customer_code'), 'customer', ['code'], unique=False)
    op.create_index(op.f('ix_customer_company_id'), 'customer', ['company_id'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code')
    )
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=False)
    op.create_index(op.f('ix_supplier_company_id'), 'supplier', ['company_id'], unique=False)
    op.create_table('user_company_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('warehouse_type', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code')
    )
    op.create_index(op.f('ix_warehouse_company_id'), 'warehouse', ['company_id'], unique=False)
    op.create_table('workflow_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type', 'version')
    )
    op.create_index(op.f('ix_workflow_definition_doc_type'), 'workflow_definition', ['doc_type'], unique=False)
    op.create_table('workflow_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('transition_name', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=False),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hooks_executed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wflog_doc', 'workflow_log', ['doc_type', 'doc_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_workflow_log_doc_id'), 'workflow_log', ['doc_id'], unique=False)
    op.create_index(op.f('ix_workflow_log_doc_type'), 'workflow_log', ['doc_type'], unique=False)
    op.create_index(op.f('ix_workflow_log_timestamp'), 'workflow_log', ['timestamp'], unique=False)
    op.create_table('account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('opening_debit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('opening_credit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('period_debit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('period_credit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('closing_debit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('closing_credit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'account_id', 'period_id')
    )
    op.create_table('customer_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('used_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('warning_threshold_pct', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'customer_id')
    )
    op.create_index(op.f('ix_customer_credit_company_id'), 'customer_credit', ['company_id'], unique=False)
    op.create_table('framework_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('rolling_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'contract_number')
    )
    op.create_index(op.f('ix_framework_contract_company_id'), 'framework_contract', ['company_id'], unique=False)
    op.create_index(op.f('ix_framework_contract_contract_number'), 'framework_contract', ['contract_number'], unique=False)
    op.create_table('label_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=True),
    sa.Column('fields_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_line', sa.String(length=20), nullable=True),
    sa.Column('is_domestic', sa.Boolean(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['material_category.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_sku'), 'material', ['sku'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('product_engineer_id', sa.Integer(), nullable=True),
    sa.Column('sales_engineer_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_annual_revenue', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('expected_mass_production_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_engineer_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['sales_engineer_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_company_id'), 'project', ['company_id'], unique=False)
    op.create_table('supplier_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('used_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('warning_threshold_pct', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'supplier_id')
    )
    op.create_index(op.f('ix_supplier_credit_company_id'), 'supplier_credit', ['company_id'], unique=False)
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(length=30), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('voucher_type', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=True),
    sa.Column('source_doc_type', sa.String(length=30), nullable=True),
    sa.Column('source_doc_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_period.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'voucher_number')
    )
    op.create_index(op.f('ix_voucher_company_id'), 'voucher', ['company_id'], unique=False)
    op.create_index(op.f('ix_voucher_voucher_number'), 'voucher', ['voucher_number'], unique=False)
    op.create_table('warehouse_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('shelf', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code')
    )
    op.create_table('workflow_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=False),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('editable_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_html', sa.Text(), nullable=True),
    sa.Column('agent_prompt', sa.Text(), nullable=True),
    sa.Column('agent_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_period.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_txn_material_date', 'inventory_transaction', ['company_id', 'material_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_transaction_date'), 'inventory_transaction', ['transaction_date'], unique=False)
    op.create_table('inventory_valuation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cost_method', sa.String(length=15), nullable=True),
    sa.Column('current_unit_cost', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('total_quantity', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'material_id')
    )
    op.create_index(op.f('ix_inventory_valuation_company_id'), 'inventory_valuation', ['company_id'], unique=False)
    op.create_table('project_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=15), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('quantity_estimate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'material_id')
    )
    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('framework_contract_id', sa.Integer(), nullable=True),
    sa.Column('sales_engineer_id', sa.Integer(), nullable=True),
    sa.Column('sales_assistant_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('shipping_method', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['framework_contract_id'], ['framework_contract.id'], ),
    sa.ForeignKeyConstraint(['sales_assistant_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['sales_engineer_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_company_id'), 'sales_order', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_order_order_number'), 'sales_order', ['order_number'], unique=True)
    op.create_table('voucher_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'line_number')
    )
    op.create_table('accounts_receivable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_receivable_company_id'), 'accounts_receivable', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_invoice_number'), 'accounts_receivable', ['invoice_number'], unique=False)
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_assistant_id', sa.Integer(), nullable=True),
    sa.Column('related_sales_order_id', sa.Integer(), nullable=True),
    sa.Column('is_stock_order', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['purchase_assistant_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['related_sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_company_id'), 'purchase_order', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_order_number'), 'purchase_order', ['order_number'], unique=True)
    op.create_table('sales_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('shipped_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_order_id', 'line_number')
    )
    op.create_table('shipment_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sa.String(length=30), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('shipping_method', sa.String(length=10), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_index(op.f('ix_shipment_request_company_id'), 'shipment_request', ['company_id'], unique=False)
    op.create_table('accounts_payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_payable_company_id'), 'accounts_payable', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounts_payable_invoice_number'), 'accounts_payable', ['invoice_number'], unique=False)
    op.create_table('goods_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_goods_receipt_company_id'), 'goods_receipt', ['company_id'], unique=False)
    op.create_table('picking_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_request.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'line_number')
    )
    op.create_table('goods_receipt_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quality_status', sa.String(length=10), nullable=True),
    sa.Column('discrepancy_note', sa.Text(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batch_number'), 'inventory', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_company_id'), 'inventory', ['company_id'], unique=False)
    op.create_index('ix_inventory_fifo', 'inventory', ['material_id', 'warehouse_id', 'received_date'], unique=False)
    op.create_index(op.f('ix_inventory_received_date'), 'inventory', ['received_date'], unique=False)
    op.create_table('picking_list_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picking_list_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('picked_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['picking_list_id'], ['picking_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_line.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_line')
    op.drop_table('picking_list_line')
    op.drop_index(op.f('ix_inventory_received_date'), table_name='inventory')
    op.drop_index('ix_inventory_fifo', table_name='inventory')
    op.drop_index(op.f('ix_inventory_company_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_batch_number'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('goods_receipt_line')
    op.drop_table('purchase_order_line')
    op.drop_table('picking_list')
    op.drop_index(op.f('ix_goods_receipt_company_id'), table_name='goods_receipt')
    op.drop_table('goods_receipt')
    op.drop_index(op.f('ix_accounts_payable_invoice_number'), table_name='accounts_payable')
    op.drop_index(op.f('ix_accounts_payable_company_id'), table_name='accounts_payable')
    op.drop_table('accounts_payable')
    op.drop_index(op.f('ix_shipment_request_company_id'), table_name='shipment_request')
    op.drop_table('shipment_request')
    op.drop_table('sales_order_line')
    op.drop_index(op.f('ix_purchase_order_order_number'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_company_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_accounts_receivable_invoice_number'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_company_id'), table_name='accounts_receivable')
    op.drop_table('accounts_receivable')
    op.drop_table('voucher_entry')
    op.drop_index(op.f('ix_sales_order_order_number'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_company_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_table('project_material')
    op.drop_table('project_activity')
    op.drop_index(op.f('ix_inventory_valuation_company_id'), table_name='inventory_valuation')
    op.drop_table('inventory_valuation')
    op.drop_index(op.f('ix_inventory_transaction_transaction_date'), table_name='inventory_transaction')
    op.drop_index('ix_inv_txn_material_date', table_name='inventory_transaction')
    op.drop_table('inventory_transaction')
    op.drop_table('workflow_transition')
    op.drop_table('warehouse_location')
    op.drop_index(op.f('ix_voucher_voucher_number'), table_name='voucher')
    op.drop_index(op.f('ix_voucher_company_id'), table_name='voucher')
    op.drop_table('voucher')
    op.drop_index(op.f('ix_supplier_credit_company_id'), table_name='supplier_credit')
    op.drop_table('supplier_credit')
    op.drop_index(op.f('ix_project_company_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_material_sku'), table_name='material')
    op.drop_table('material')
    op.drop_table('label_template')
    op.drop_index(op.f('ix_framework_contract_contract_number'), table_name='framework_contract')
    op.drop_index(op.f('ix_framework_contract_company_id'), table_name='framework_contract')
    op.drop_table('framework_contract')
    op.drop_index(op.f('ix_customer_credit_company_id'), table_name='customer_credit')
    op.drop_table('customer_credit')
    op.drop_table('account_balance')
    op.drop_index(op.f('ix_workflow_log_timestamp'), table_name='workflow_log')
    op.drop_index(op.f('ix_workflow_log_doc_type'), table_name='workflow_log')
    op.drop_index(op.f('ix_workflow_log_doc_id'), table_name='workflow_log')
    op.drop_index('ix_wflog_doc', table_name='workflow_log')
    op.drop_table('workflow_log')
    op.drop_index(op.f('ix_workflow_definition_doc_type'), table_name='workflow_definition')
    op.drop_table('workflow_definition')
    op.drop_index(op.f('ix_warehouse_company_id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_table('user_company_access')
    op.drop_index(op.f('ix_supplier_company_id'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_customer_company_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_code'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_agent_log_timestamp'), table_name='agent_log')
    op.drop_table('agent_log')
    op.drop_table('accounting_period')
    op.drop_table('user_account')
    op.drop_table('fiscal_year')
    op.drop_index(op.f('ix_account_code'), table_name='account')
    op.drop_table('account')
    op.drop_table('material_category')
    op.drop_index(op.f('ix_knowledge_entry_entry_type'), table_name='knowledge_entry')
    op.drop_table('knowledge_entry')
    op.drop_index(op.f('ix_exchange_rate_effective_date'), table_name='exchange_rate')
    op.drop_table('exchange_rate')
    op.drop_table('company')
    op.drop_table('agent_definition')
    # ### end Alembic commands ###
